#!/bin/bash
set -e
set -o pipefail

cat lib/secret/secret.dart.sample | sed \
  -e "s|\[REVENUECAT_PUBLIC_API_KEY_IOS\]|$REVENUECAT_PUBLIC_API_KEY_IOS|g" \
  -e "s|\[REVENUECAT_PUBLIC_API_KEY_ANDROID\]|$REVENUECAT_PUBLIC_API_KEY_ANDROID|g" \
  -e "s|\[IOS_ADMOB_NATIVE_ADVANCE_IDENTIFIER\]|$IOS_ADMOB_NATIVE_ADVANCE_IDENTIFIER|g" \
  -e "s|\[ANDROID_ADMOB_NATIVE_ADVANCE_IDENTIFIER\]|$ANDROID_ADMOB_NATIVE_ADVANCE_IDENTIFIER|g" \
  -e "s|\[IOS_ADMOB_BANNER_IDENTIFIER\]|$IOS_ADMOB_BANNER_IDENTIFIER|g" \
  -e "s|\[ANDROID_ADMOB_BANNER_IDENTIFIER\]|$ANDROID_ADMOB_BANNER_IDENTIFIER|g" \
> lib/secret/secret.dart
